### ISSUE TITLE
Background mode

### ISSUE THREAD

**Issue by qahor0v** [lowski/screenshooter#1]
Helllo! Does this package also work in the background mode?

**Comment by lowski** [comment]
Hey there! Could you please specify what you mean by background mode?

**Comment by qahor0v** [comment]
> Hey there! Could you please specify what you mean by background mode?

Hello. I am creating an app for parents to monitor their child. The application should take a screenshot of the phone's screen every 10 minutes and send it to the parent. This should also work in the background. That's what I meant

**Comment by lowski** [comment]
Ah, I see. This package is not suitable for that use case. It can automatically take predefined screenshots of your app through the iOS Simulator. It does not run on real devices nor can it be shipped to users.
